import { pgTable, uuid, text, timestamp, jsonb, index, integer } from 'drizzle-orm/pg-core';
import { organizations } from './organizations.js';
import { aiConversations } from './conversations.js';

// ============================================
// Type Definitions (exported for use in other modules)
// ============================================

/**
 * Document types that can be generated by the AI
 */
export type DocumentType =
  | 'payment_report'      // Payment/financial summary
  | 'people_list'         // List of people with filters
  | 'program_report'      // Program enrollment/status
  | 'interview_schedule'  // Interview schedule/summary
  | 'event_summary'       // Event participation report
  | 'custom_report';      // Custom/ad-hoc reports

/**
 * Document format (file type)
 */
export type DocumentFormat = 'pdf' | 'csv';

/**
 * Document status
 */
export type DocumentStatus = 'generating' | 'ready' | 'failed' | 'archived';

/**
 * Metadata stored in JSONB for document context
 */
export interface DocumentMetadata {
  /** Query/filters used to generate the document */
  query?: Record<string, unknown>;
  /** Number of records in the document */
  recordCount?: number;
  /** Column headers for CSV or table data */
  columns?: string[];
  /** Any error message if generation failed */
  error?: string;
  /** Generation options (e.g., date range, filters) */
  options?: Record<string, unknown>;
}

/**
 * AI Documents table - stores documents generated by the AI assistant
 * Files are stored in Supabase Storage, metadata here
 */
export const aiDocuments = pgTable('ai_documents', {
  id: uuid('id').primaryKey().defaultRandom(),
  organizationId: uuid('organization_id').notNull().references(() => organizations.id),

  // Optional link to conversation that created this document
  conversationId: uuid('conversation_id').references(() => aiConversations.id, { onDelete: 'set null' }),

  // Document identification
  title: text('title').notNull(), // Display name, e.g., "דוח תשלומים דצמבר 2024"
  description: text('description'), // Brief description of document contents

  // Type and format
  documentType: text('document_type').$type<DocumentType>().notNull(),
  format: text('format').$type<DocumentFormat>().notNull(),

  // Storage location
  storagePath: text('storage_path'), // Path in Supabase Storage bucket
  fileName: text('file_name'), // Original file name with extension

  // File details
  fileSize: integer('file_size'), // Size in bytes
  mimeType: text('mime_type'), // MIME type (application/pdf, text/csv)

  // Status
  status: text('status').$type<DocumentStatus>().default('generating').notNull(),

  // Flexible metadata
  metadata: jsonb('metadata').$type<DocumentMetadata>(),

  // User who created the document
  createdByUserId: uuid('created_by_user_id'),
  createdByEmail: text('created_by_email'),

  // Timestamps
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at').defaultNow().notNull(),
}, (table) => [
  index('ai_documents_org_idx').on(table.organizationId),
  index('ai_documents_conversation_idx').on(table.conversationId),
  index('ai_documents_type_idx').on(table.documentType),
  index('ai_documents_status_idx').on(table.status),
  index('ai_documents_created_idx').on(table.createdAt),
]);
