-- Migration: Add AI Documents table
-- Generated: 2025-12-26
-- Description: Stores documents/reports generated by AI assistant (PDF, CSV)
-- Files are stored in Supabase Storage, metadata here

-- ============================================
-- AI Documents Table
-- ============================================
CREATE TABLE IF NOT EXISTS ai_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id),

  -- Optional link to conversation that created this document
  conversation_id UUID REFERENCES ai_conversations(id) ON DELETE SET NULL,

  -- Document identification
  title TEXT NOT NULL,
  description TEXT,

  -- Type and format
  document_type TEXT NOT NULL CHECK (document_type IN (
    'payment_report',
    'people_list',
    'program_report',
    'interview_schedule',
    'event_summary',
    'custom_report'
  )),
  format TEXT NOT NULL CHECK (format IN ('pdf', 'csv')),

  -- Storage location (Supabase Storage)
  storage_path TEXT,
  file_name TEXT,

  -- File details
  file_size INTEGER,
  mime_type TEXT,

  -- Status
  status TEXT NOT NULL DEFAULT 'generating' CHECK (status IN (
    'generating',
    'ready',
    'failed',
    'archived'
  )),

  -- Flexible metadata (query params, record count, columns, etc.)
  metadata JSONB,

  -- User who created the document
  created_by_user_id UUID,
  created_by_email TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- ============================================
-- Indexes
-- ============================================
CREATE INDEX IF NOT EXISTS ai_documents_org_idx ON ai_documents(organization_id);
CREATE INDEX IF NOT EXISTS ai_documents_conversation_idx ON ai_documents(conversation_id);
CREATE INDEX IF NOT EXISTS ai_documents_type_idx ON ai_documents(document_type);
CREATE INDEX IF NOT EXISTS ai_documents_status_idx ON ai_documents(status);
CREATE INDEX IF NOT EXISTS ai_documents_created_idx ON ai_documents(created_at DESC);

-- ============================================
-- Updated_at trigger
-- ============================================
CREATE OR REPLACE FUNCTION update_ai_documents_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER ai_documents_updated_at
  BEFORE UPDATE ON ai_documents
  FOR EACH ROW
  EXECUTE FUNCTION update_ai_documents_updated_at();

-- ============================================
-- RLS Policies (single-tenant - all authenticated users can access)
-- ============================================
ALTER TABLE ai_documents ENABLE ROW LEVEL SECURITY;

-- Read all documents
CREATE POLICY "ai_documents_read_all" ON ai_documents
  FOR SELECT TO authenticated
  USING (true);

-- Insert documents
CREATE POLICY "ai_documents_insert" ON ai_documents
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- Update documents
CREATE POLICY "ai_documents_update" ON ai_documents
  FOR UPDATE TO authenticated
  USING (true)
  WITH CHECK (true);

-- Delete documents (only if archived)
CREATE POLICY "ai_documents_delete" ON ai_documents
  FOR DELETE TO authenticated
  USING (status = 'archived');

-- Service role can do everything
CREATE POLICY "ai_documents_service_all" ON ai_documents
  FOR ALL TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================
-- Create Storage Bucket for AI Documents
-- ============================================
-- Note: This needs to be run separately or via Supabase dashboard
-- INSERT INTO storage.buckets (id, name, public)
-- VALUES ('ai-documents', 'ai-documents', false)
-- ON CONFLICT (id) DO NOTHING;

-- Storage policies for ai-documents bucket (run via dashboard or separate migration)
-- CREATE POLICY "ai_documents_storage_read" ON storage.objects
--   FOR SELECT TO authenticated
--   USING (bucket_id = 'ai-documents');
--
-- CREATE POLICY "ai_documents_storage_insert" ON storage.objects
--   FOR INSERT TO authenticated
--   WITH CHECK (bucket_id = 'ai-documents');
--
-- CREATE POLICY "ai_documents_storage_service" ON storage.objects
--   FOR ALL TO service_role
--   USING (bucket_id = 'ai-documents')
--   WITH CHECK (bucket_id = 'ai-documents');
